#!/bin/bash

ROOT="$3"; if [ -z "${ROOT}" ] || [ "${ROOT}" = "/" ]; then ROOT=""; fi
OS=$(defaults read "${ROOT}/System/Library/CoreServices/SystemVersion" ProductVersion)
ME=$0

# Specify the shortname, include kcpassword file(s) in your payload.
SHORTNAME="YOURSHORTNAME"

# Payload
[ -e "${ROOT}/tmp/kcpassword.${OS}" ] && sudo cp -f "${ROOT}/tmp/kcpassword.${OS}" "${ROOT}/etc/kcpassword" || exit 1
[ -e "${ROOT}/etc/kcpassword" ] && sudo chown root:wheel "${ROOT}/etc/kcpassword"
[ -e "${ROOT}/etc/kcpassword" ] && sudo chmod 600 "${ROOT}/etc/kcpassword"
[ -e "${ROOT}/etc/kcpassword.disabled" ] && sudo srm -Rf "${ROOT}/etc/kcpassword.disabled"

# com.apple.loginwindow.plist
[ "${SHORTNAME}" != "" ] && sudo defaults write "${ROOT}/Library/Preferences/com.apple.loginwindow" autoLoginUser -string "${SHORTNAME}" || exit 1
[ -e "${ROOT}/Library/Preferences/com.apple.loginwindow.plist" ] && sudo chown root:wheel "${ROOT}/Library/Preferences/com.apple.loginwindow.plist"
[ -e "${ROOT}/Library/Preferences/com.apple.loginwindow.plist" ] && sudo chmod 644 "${ROOT}/Library/Preferences/com.apple.loginwindow.plist"
[ -e "${ROOT}/Library/Preferences/com.apple.loginwindow.plist.lockfile" ] && sudo srm -Rf "${ROOT}/Library/Preferences/com.apple.loginwindow.plist.lockfile"

exit 0
