#!/bin/bash
# chris.gerke@gmail.com

ROOT="$3"; if [ -z "${ROOT}" ] || [ "${ROOT}" = "/" ]; then ROOT=""; fi
OS=$(sudo defaults read "${ROOT}/System/Library/CoreServices/SystemVersion" ProductVersion)
ME=$0

LCT="AppleUserLibrary"
ORG="cmg"

# LaunchAgent
sudo defaults write "${ROOT}/Library/LaunchAgents/com.${ORG}.${LCT}" Label "com.${ORG}.${LCT}"
sudo defaults write "${ROOT}/Library/LaunchAgents/com.${ORG}.${LCT}" RunAtLoad -bool TRUE
sudo defaults write "${ROOT}/Library/LaunchAgents/com.${ORG}.${LCT}" ProgramArguments -array "/bin/sh" "-c" "/bin/sleep 10; /usr/bin/chflags nohidden ~/Library"
sudo chown root:wheel "${ROOT}/Library/LaunchAgents/com.${ORG}.${LCT}.plist"
sudo chmod 644 "${ROOT}/Library/LaunchAgents/com.${ORG}.${LCT}.plist"

# Load if booted
if [ -z "${ROOT}" ] || [ "${ROOT}" = "" ]; then sudo launchctl load -w "${ROOT}/Library/LaunchAgents/com.${ORG}.${LCT}.plist"; fi

exit 0
