#!/bin/bash
# chris.gerke@gmail.com

ME=$0
OS=$(sudo defaults read "${ROOT}/System/Library/CoreServices/SystemVersion" ProductVersion)
ROOT="$3"; if [ -z "${ROOT}" ] || [ "${ROOT}" = "/" ]; then ROOT=""; fi

LCT="AppleSharingSSH"
ORG="cmg"

# LaunchDaemon
sudo defaults write "${ROOT}/Library/LaunchDaemons/com.${ORG}.${LCT}" Label "com.${ORG}.${LCT}"
sudo defaults write "${ROOT}/Library/LaunchDaemons/com.${ORG}.${LCT}" RunAtLoad -bool TRUE
sudo defaults write "${ROOT}/Library/LaunchDaemons/com.${ORG}.${LCT}" ProgramArguments -array "/usr/sbin/systemsetup" "-setremotelogin" "on"
sudo chown root:wheel "${ROOT}/Library/LaunchDaemons/com.${ORG}.${LCT}.plist"
sudo chmod 644 "${ROOT}/Library/LaunchDaemons/com.${ORG}.${LCT}.plist"

# Load if booted
if [ -z "${ROOT}" ] || [ "${ROOT}" = "" ]; then sudo launchctl load -w "${ROOT}/Library/LaunchDaemons/com.${ORG}.${LCT}.plist"; fi

exit 0
