#!/bin/bash
# chris.gerke@gmail.com

ROOT="$3"; if [ -z "${ROOT}" ] || [ "${ROOT}" = "/" ]; then ROOT=""; fi
OS=$(sudo defaults read "${ROOT}/System/Library/CoreServices/SystemVersion" ProductVersion)
ME=$0

LCT="AppleGateKeeper"
ORG="cmg"

# LaunchDaemon (daemon because softwareupdate requires root)
sudo defaults write "${ROOT}/Library/LaunchDaemons/${LCT}" Label "com.${ORG}.${LCT}"
sudo defaults write "${ROOT}/Library/LaunchDaemons/${LCT}" RunAtLoad -bool TRUE
sudo defaults write "${ROOT}/Library/LaunchDaemons/${LCT}" ProgramArguments -array "/usr/sbin/spctl" "--master-disable"
sudo chown root:wheel "${ROOT}/Library/LaunchDaemons/com.${ORG}.${LCT}.plist"
sudo chmod 644 "${ROOT}/Library/LaunchDaemons/com.${ORG}.${LCT}.plist" 

# Load if booted
if [ -z "${ROOT}" ] || [ "${ROOT}" = "" ]; then sudo launchctl load -w "${ROOT}/Library/LaunchDaemons/com.${ORG}.${LCT}.plist"; fi

exit 0
