#!/bin/bash

ROOT="$3"; if [ -z "${ROOT}" ] || [ "${ROOT}" = "/" ]; then ROOT=""; fi
OS=$(defaults read "${ROOT}/System/Library/CoreServices/SystemVersion" ProductVersion)
ME=$0

[ -e "${ROOT}/Library/Preferences/com.apple.dockfixup.plist" ] && sudo mv "${ROOT}/Library/Preferences/com.apple.dockfixup.plist" "${ROOT}/Library/Preferences/com.apple.dockfixup.plist.bak"

exit 0
