#!/bin/bash
# chris.gerke@gmail.com

ROOT="$3"; if [ -z "${ROOT}" ] || [ "${ROOT}" = "/" ]; then ROOT=""; fi
OS=$(sudo defaults read "${ROOT}/System/Library/CoreServices/SystemVersion" ProductVersion)
ME=$0

FDATE=$(date +"%Y%m%d%H%M%S")

# Detect Plistbuddy, it rocks.
[ -e /usr/libexec/PlistBuddy ] && PB="/usr/libexec/PlistBuddy" || exit 1

# Backup Original
[ -e "${ROOT}/etc/authorization" ] && sudo cp -f "${ROOT}/etc/authorization" "${ROOT}/etc/authorization.${FDATE}" || exit 1

# Allow date & time preference pane access.
sudo "${PB}" -c "set rights:system.preferences.datetime:class allow" "${ROOT}/etc/authorization"
sudo "${PB}" -c "delete rights:system.preferences.datetime:shared" "${ROOT}/etc/authorization"
sudo "${PB}" -c "delete rights:system.preferences.datetime:group" "${ROOT}/etc/authorization"

# Permissions
sudo chown root:wheel "${ROOT}/etc/authorization"
sudo chmod 644 "${ROOT}/etc/authorization"

exit 0
