#!/bin/sh
# Profiles : Payload required. VPN Profiles. WiFi Profiles
# chris.gerke@gmail.com

# // fix
ROOT="$3"; if [ -z "${ROOT}" ] || [ "${ROOT}" = "/" ]; then ROOT=""; fi

# Remove
#for PROFILE in `sudo ls ${SCRIPT_DIR}/PAYLOAD/REMOVE`
#do
# sudo /usr/bin/profiles -R -F "${SCRIPT_DIR}/PAYLOAD/REMOVE/${PROFILE}"
#done
 
# Add for laptops
/usr/sbin/system_profiler SPHardwareDataType | /usr/bin/grep "Model Identifier" | /usr/bin/grep "Book"
if [ "$?" = "0" ]; then
 for PROFILE in `sudo ls ${ROOT}/usr/local/bin/*.mobileconfig`
 do
  sudo /usr/bin/profiles -I -F "${PROFILE}"
 done
fi

# Clean
for PROFILE in `sudo ls ${ROOT}/usr/local/bin/*.mobileconfig`
do
 sudo /bin/rm -Rf "${PROFILE}"
done

# Unload
if [ -r "/Library/LaunchDaemons/AppleProfiles.plist" ]; then
 sudo /usr/bin/srm "/Library/LaunchDaemons/AppleProfiles.plist"
fi

# Self destruct
sudo /usr/bin/srm "${0}"

exit 0