#!/bin/bash

ROOT="$3"; if [ -z "${ROOT}" ] || [ "${ROOT}" = "/" ]; then ROOT=""; fi
OS=$(defaults read "${ROOT}/System/Library/CoreServices/SystemVersion" ProductVersion)
ME=$0

LNA="AppleLaunchdSharingARD"
LND="AppleLaunchdSharingSSH"

BANNER="Unauthorized access to these resources is prohibited."
VNCPWD="YOURVNCPASSWORD"

# MOTD Banner
sudo echo " " > "${ROOT}/etc/motd"
sudo echo "${BANNER}" >> "${ROOT}/etc/motd"
sudo echo " " >> "${ROOT}/etc/motd"

# VNC Password
sudo echo "${VNCPWD}" > "${ROOT}/Library/Preferences/com.apple.VNCSettings.txt"
sudo chown -R root:wheel "${ROOT}/Library/Preferences/com.apple.VNCSettings.txt"
sudo chmod -R 600 "${ROOT}/Library/Preferences/com.apple.VNCSettings.txt"

# ARD binaries
[ -e "${ROOT}/usr/local/bin/ard" ] && sudo chown root:wheel "${ROOT}/usr/local/bin/ard"
[ -e "${ROOT}/usr/local/bin/ard" ] && sudo chmod 755 "${ROOT}/usr/local/bin/ard"
[ -e "${ROOT}/usr/local/bin/ard" ] && sudo chmod u+s "${ROOT}/usr/local/bin/ard"
[ -e "${ROOT}/usr/local/bin/ardon" ] && sudo chown root:wheel "${ROOT}/usr/local/bin/ardon"
[ -e "${ROOT}/usr/local/bin/ardon" ] && sudo chmod 755 "${ROOT}/usr/local/bin/ardon"
[ -e "${ROOT}/usr/local/bin/ardon" ] && sudo chmod u+s "${ROOT}/usr/local/bin/ardon"
[ -e "${ROOT}/usr/local/bin/ardoff" ] && sudo chown root:wheel "${ROOT}/usr/local/bin/ardoff"
[ -e "${ROOT}/usr/local/bin/ardoff" ] && sudo chmod 755 "${ROOT}/usr/local/bin/ardoff"
[ -e "${ROOT}/usr/local/bin/ardoff" ] && sudo chmod u+s "${ROOT}/usr/local/bin/ardoff"
[ -e "${ROOT}/usr/local/bin/sshon" ] && sudo chown root:wheel "${ROOT}/usr/local/bin/sshon"
[ -e "${ROOT}/usr/local/bin/sshon" ] && sudo chmod 755 "${ROOT}/usr/local/bin/sshon"
[ -e "${ROOT}/usr/local/bin/sshon" ] && sudo chmod u+s "${ROOT}/usr/local/bin/sshon"

# LaunchAgent
sudo defaults write "${ROOT}/Library/LaunchAgents/${LNA}" Label "${LNA}"
sudo defaults write "${ROOT}/Library/LaunchAgents/${LNA}" RunAtLoad -bool TRUE
sudo defaults write "${ROOT}/Library/LaunchAgents/${LNA}" ProgramArguments -array "/bin/sh" "-c" "/usr/local/bin/ard"
sudo chown root:wheel "${ROOT}/Library/LaunchAgents/${LNA}.plist"
sudo chmod 644 "${ROOT}/Library/LaunchAgents/${LNA}.plist"

# Load if booted
if [ -z "${ROOT}" ] || [ "${ROOT}" = "" ]; then sudo launchctl load -w "${ROOT}/Library/LaunchAgents/${LNA}.plist"; fi

# LaunchDaemon
sudo defaults write "${ROOT}/Library/LaunchDaemons/${LND}" Label "${LND}"
sudo defaults write "${ROOT}/Library/LaunchDaemons/${LND}" RunAtLoad -bool TRUE
sudo defaults write "${ROOT}/Library/LaunchDaemons/${LND}" ProgramArguments -array "/usr/sbin/systemsetup" "-setremotelogin" "on"
sudo chown root:wheel "${ROOT}/Library/LaunchDaemons/${LND}.plist"
sudo chmod 644 "${ROOT}/Library/LaunchDaemons/${LND}.plist"

# Load if booted
if [ -z "${ROOT}" ] || [ "${ROOT}" = "" ]; then sudo launchctl load -w "${ROOT}/Library/LaunchDaemons/${LND}.plist"; fi

exit 0
