#!/bin/bash

ROOT="$3"; if [ -z "${ROOT}" ] || [ "${ROOT}" = "/" ]; then ROOT=""; fi
OS=$(defaults read "${ROOT}/System/Library/CoreServices/SystemVersion" ProductVersion)
ME=$0

FDATE=$(date +"%Y%m%d%H%M%S")

# Detect Plistbuddy, it rocks.
[ -e /usr/libexec/PlistBuddy ] && PB="/usr/libexec/PlistBuddy" || exit 1

# Backup Original
[ -e "${ROOT}/etc/authorization" ] && sudo cp -f "${ROOT}/etc/authorization" "${ROOT}/etc/authorization.${FDATE}" || exit 1

# Allow date & time preference pane access.
sudo "${PB}" -c "set rights:system.preferences.datetime:class allow" "${ROOT}/etc/authorization"
sudo "${PB}" -c "delete rights:system.preferences.datetime:shared" "${ROOT}/etc/authorization"
sudo "${PB}" -c "delete rights:system.preferences.datetime:group" "${ROOT}/etc/authorization"

# Allow DVD region setting rights
sudo "${PB}" -c "add rights:system.device.dvd.setregion.change dict" "${ROOT}/etc/authorization"
sudo "${PB}" -c "add rights:system.device.dvd.setregion.change:class string" "${ROOT}/etc/authorization"
sudo "${PB}" -c "set rights:system.device.dvd.setregion.change:class allow" "${ROOT}/etc/authorization"
sudo "${PB}" -c "delete rights:system.device.dvd.setregion.change:shared" "${ROOT}/etc/authorization"
sudo "${PB}" -c "delete rights:system.device.dvd.setregion.change:group" "${ROOT}/etc/authorization"

# Allow DVD region initial setting rights
sudo "${PB}" -c "set rights:system.device.dvd.setregion.initial:class allow" "${ROOT}/etc/authorization"
sudo "${PB}" -c "delete rights:system.device.dvd.setregion.initial:shared" "${ROOT}/etc/authorization"
sudo "${PB}" -c "delete rights:system.device.dvd.setregion.initial:group" "${ROOT}/etc/authorization"

# Allow network preference pane access
sudo "${PB}" -c "set rights:system.preferences.network:class allow" "${ROOT}/etc/authorization"
sudo "${PB}" -c "delete rights:system.preferences.network:shared" "${ROOT}/etc/authorization"
sudo "${PB}" -c "delete rights:system.preferences.network:group" "${ROOT}/etc/authorization"

# Allow preference panes
sudo "${PB}" -c "set rights:system.preferences:class allow" "${ROOT}/etc/authorization"
sudo "${PB}" -c "delete rights:system.preferences:shared" "${ROOT}/etc/authorization"
sudo "${PB}" -c "delete rights:system.preferences:group" "${ROOT}/etc/authorization"

# Change ${ROOT}/etc/authorization to allow all users to open preference panes
sudo "${PB}" -c "set rights:system.preferences.printing:class allow" "${ROOT}/etc/authorization"
sudo "${PB}" -c "delete rights:system.preferences.printing:shared" "${ROOT}/etc/authorization"
sudo "${PB}" -c "delete rights:system.preferences.printing:group" "${ROOT}/etc/authorization"

# Allow print admin rights
sudo "${PB}" -c "set rights:system.print.admin:class allow" "${ROOT}/etc/authorization"
sudo "${PB}" -c "delete rights:system.print.admin:group" "${ROOT}/etc/authorization"
sudo "${PB}" -c "delete rights:system.print.admin:shared" "${ROOT}/etc/authorization"

# Allow printing manager rights
sudo "${PB}" -c "set rights:system.printingmanager:class allow" "${ROOT}/etc/authorization"
sudo "${PB}" -c "delete rights:system.printingmanager:rule" "${ROOT}/etc/authorization"

# Allow admin to unlock screensaver, test this... changed in 10.7
sudo "${PB}" -c "set :rights:system.login.screensaver:comment \"(Use SecurityAgent.) The owner or any administrator can unlock the screensaver.\"" "${ROOT}/etc/authorization"

# Permissions
sudo chown root:wheel "${ROOT}/etc/authorization"
sudo chmod 644 "${ROOT}/etc/authorization"

exit 0
