#!/bin/bash
# chris.gerke@gmail.com

ME=$0
OS=$(sudo defaults read "${ROOT}/System/Library/CoreServices/SystemVersion" ProductVersion)
ROOT="$3"; if [ -z "${ROOT}" ] || [ "${ROOT}" = "/" ]; then ROOT=""; fi

LCT="com.apple.javadisabler"

# Disable
[ -e "${ROOT}/System/Library/LaunchAgents/${LCT}.plist" ] && sudo defaults write "${ROOT}/System/Library/LaunchAgents/${LCT}" "RunAtLoad" "No"
[ -e "${ROOT}/System/Library/LaunchAgents/${LCT}.plist" ] && sudo chown root:wheel "${ROOT}/System/Library/LaunchAgents/${LCT}.plist"
[ -e "${ROOT}/System/Library/LaunchAgents/${LCT}.plist" ] && sudo chmod 644 "${ROOT}/System/Library/LaunchAgents/${LCT}.plist"


exit 0
